
// This file has been generated by the GUI designer. Do not modify.
namespace cottontail.widgets
{
	public partial class TabLabel
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget cottontail.widgets.TabLabel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "cottontail.widgets.TabLabel";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
