
// This file has been generated by the GUI designer. Do not modify.
namespace cottontail
{
	public partial class DataGrid
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget cottontail.DataGrid
			global::Stetic.BinContainer.Attach (this);
			this.Name = "cottontail.DataGrid";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
