
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action preferencesAction;
	private global::Gtk.Action executeAction;
	private global::Gtk.Action stopAction;
	private global::Gtk.Action EditAction;
	private global::Gtk.Action AddDatabaseAction;
	private global::Gtk.Action AddRabbitExchangeAction;
	private global::Gtk.Action RunAction;
	private global::Gtk.Action saveAction1;
	private global::Gtk.Action openAction;
	private global::Gtk.Action ProjectAction;
	private global::Gtk.Action AddScriptAction;
	private global::Gtk.Action newAction1;
	private global::Gtk.Action openAction1;
	private global::Gtk.Action saveAction;
	private global::Gtk.Action saveAsAction;
	private global::Gtk.Action newAction2;
	private global::Gtk.Action saveAsAction1;
	private global::Gtk.Action preferencesAction1;
	private global::Gtk.Action executeAction1;
	private global::Gtk.Action saveAsAction2;
	private global::Gtk.Action CloseAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.VBox vbox3;
	private global::Gtk.MenuBar menubar2;
	private global::Gtk.Toolbar toolbar1;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView treeviewProject;
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.NodeView nodeview3;
	private global::Gtk.Label label1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	private global::Gtk.TextView scriptTextView;
	private global::Gtk.Label label2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView textviewLog;
	private global::Gtk.Statusbar statusbar2;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.preferencesAction = new global::Gtk.Action ("preferencesAction", null, null, "gtk-preferences");
		w1.Add (this.preferencesAction, null);
		this.executeAction = new global::Gtk.Action ("executeAction", null, null, "gtk-execute");
		w1.Add (this.executeAction, null);
		this.stopAction = new global::Gtk.Action ("stopAction", null, null, "gtk-stop");
		w1.Add (this.stopAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.EditAction, null);
		this.AddDatabaseAction = new global::Gtk.Action ("AddDatabaseAction", global::Mono.Unix.Catalog.GetString ("Add Database..."), null, null);
		this.AddDatabaseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Database...");
		w1.Add (this.AddDatabaseAction, null);
		this.AddRabbitExchangeAction = new global::Gtk.Action ("AddRabbitExchangeAction", global::Mono.Unix.Catalog.GetString ("Add Rabbit Exchange..."), null, null);
		this.AddRabbitExchangeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Rabbit Exchange...");
		w1.Add (this.AddRabbitExchangeAction, null);
		this.RunAction = new global::Gtk.Action ("RunAction", global::Mono.Unix.Catalog.GetString ("Run"), null, null);
		this.RunAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Run");
		w1.Add (this.RunAction, null);
		this.saveAction1 = new global::Gtk.Action ("saveAction1", global::Mono.Unix.Catalog.GetString ("_Save"), null, "gtk-save");
		this.saveAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Save");
		w1.Add (this.saveAction1, null);
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.ProjectAction = new global::Gtk.Action ("ProjectAction", global::Mono.Unix.Catalog.GetString ("Project"), null, null);
		this.ProjectAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Project");
		w1.Add (this.ProjectAction, null);
		this.AddScriptAction = new global::Gtk.Action ("AddScriptAction", global::Mono.Unix.Catalog.GetString ("Add Script..."), null, null);
		this.AddScriptAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Script...");
		w1.Add (this.AddScriptAction, null);
		this.newAction1 = new global::Gtk.Action ("newAction1", global::Mono.Unix.Catalog.GetString ("_New"), null, "gtk-new");
		this.newAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_New");
		w1.Add (this.newAction1, null);
		this.openAction1 = new global::Gtk.Action ("openAction1", global::Mono.Unix.Catalog.GetString ("_Open"), null, "gtk-open");
		this.openAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
		w1.Add (this.openAction1, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("_Save"), null, "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Save");
		w1.Add (this.saveAction, null);
		this.saveAsAction = new global::Gtk.Action ("saveAsAction", global::Mono.Unix.Catalog.GetString ("Save _As"), null, "gtk-save-as");
		this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save _As");
		w1.Add (this.saveAsAction, null);
		this.newAction2 = new global::Gtk.Action ("newAction2", null, null, "gtk-new");
		w1.Add (this.newAction2, null);
		this.saveAsAction1 = new global::Gtk.Action ("saveAsAction1", null, null, "gtk-save-as");
		w1.Add (this.saveAsAction1, null);
		this.preferencesAction1 = new global::Gtk.Action ("preferencesAction1", global::Mono.Unix.Catalog.GetString ("_Preferences"), null, "gtk-preferences");
		this.preferencesAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Preferences");
		w1.Add (this.preferencesAction1, null);
		this.executeAction1 = new global::Gtk.Action ("executeAction1", global::Mono.Unix.Catalog.GetString ("_Execute"), null, "gtk-execute");
		this.executeAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Execute");
		w1.Add (this.executeAction1, null);
		this.saveAsAction2 = new global::Gtk.Action ("saveAsAction2", global::Mono.Unix.Catalog.GetString ("Save _As"), null, "gtk-save-as");
		this.saveAsAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save _As");
		w1.Add (this.saveAsAction2, null);
		this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("_Close"), null, null);
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Close");
		w1.Add (this.CloseAction, "<Primary>w");
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quitAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("CottonTail");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='ProjectAction' action='ProjectAction'><menuitem name='newAction1' action='newAction1'/><menuitem name='openAction1' action='openAction1'/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction2' action='saveAsAction2'/><separator/><menuitem name='CloseAction' action='CloseAction'/><menuitem name='quitAction' action='quitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='AddDatabaseAction' action='AddDatabaseAction'/><separator/><menuitem name='AddRabbitExchangeAction' action='AddRabbitExchangeAction'/><separator/><menuitem name='AddScriptAction' action='AddScriptAction'/><separator/><menuitem name='preferencesAction1' action='preferencesAction1'/></menu><menu name='RunAction' action='RunAction'><menuitem name='executeAction1' action='executeAction1'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox3.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='newAction2' action='newAction2'/><toolitem name='openAction' action='openAction'/><toolitem name='saveAction1' action='saveAction1'/><toolitem name='saveAsAction1' action='saveAsAction1'/><separator/><toolitem name='preferencesAction' action='preferencesAction'/><separator/><toolitem name='executeAction' action='executeAction'/><toolitem name='stopAction' action='stopAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox3.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.toolbar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 232;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeviewProject = new global::Gtk.TreeView ();
		this.treeviewProject.CanFocus = true;
		this.treeviewProject.Name = "treeviewProject";
		this.GtkScrolledWindow.Add (this.treeviewProject);
		this.hpaned1.Add (this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
		w5.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 229;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 1;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.nodeview3 = new global::Gtk.NodeView ();
		this.nodeview3.CanFocus = true;
		this.nodeview3.Name = "nodeview3";
		this.GtkScrolledWindow2.Add (this.nodeview3);
		this.notebook1.Add (this.GtkScrolledWindow2);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
		this.notebook1.SetTabLabel (this.GtkScrolledWindow2, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.scriptTextView = new global::Gtk.TextView ();
		this.scriptTextView.CanFocus = true;
		this.scriptTextView.Name = "scriptTextView";
		this.GtkScrolledWindow3.Add (this.scriptTextView);
		this.notebook1.Add (this.GtkScrolledWindow3);
		global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow3]));
		w9.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
		this.notebook1.SetTabLabel (this.GtkScrolledWindow3, this.label2);
		this.label2.ShowAll ();
		this.vpaned1.Add (this.notebook1);
		global::Gtk.Paned.PanedChild w10 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.notebook1]));
		w10.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textviewLog = new global::Gtk.TextView ();
		this.textviewLog.CanFocus = true;
		this.textviewLog.Name = "textviewLog";
		this.GtkScrolledWindow1.Add (this.textviewLog);
		this.vpaned1.Add (this.GtkScrolledWindow1);
		this.hpaned1.Add (this.vpaned1);
		this.vbox3.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hpaned1]));
		w14.Position = 2;
		// Container child vbox3.Gtk.Box+BoxChild
		this.statusbar2 = new global::Gtk.Statusbar ();
		this.statusbar2.Name = "statusbar2";
		this.statusbar2.Spacing = 6;
		this.vbox3.Add (this.statusbar2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.statusbar2]));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 932;
		this.DefaultHeight = 558;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.preferencesAction.Activated += new global::System.EventHandler (this.OnPreferences);
		this.executeAction.Activated += new global::System.EventHandler (this.OnExecute);
		this.stopAction.Activated += new global::System.EventHandler (this.OnStop);
		this.AddDatabaseAction.Activated += new global::System.EventHandler (this.OnAddDatabase);
		this.AddRabbitExchangeAction.Activated += new global::System.EventHandler (this.OnAddRabbitExchange);
		this.saveAction1.Activated += new global::System.EventHandler (this.OnSaveProject);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenProject);
		this.AddScriptAction.Activated += new global::System.EventHandler (this.OnAddScript);
		this.newAction1.Activated += new global::System.EventHandler (this.OnNewProject);
		this.openAction1.Activated += new global::System.EventHandler (this.OnOpenProject);
		this.saveAction.Activated += new global::System.EventHandler (this.OnSaveProject);
		this.saveAsAction.Activated += new global::System.EventHandler (this.OnSaveProjectAs);
		this.newAction2.Activated += new global::System.EventHandler (this.OnNewProject);
		this.saveAsAction1.Activated += new global::System.EventHandler (this.OnSaveProjectAs);
		this.preferencesAction1.Activated += new global::System.EventHandler (this.OnPreferences);
		this.executeAction1.Activated += new global::System.EventHandler (this.OnExecute);
		this.CloseAction.Activated += new global::System.EventHandler (this.OnCloseProject);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuit);
	}
}
